### ISSUE TITLE
Restore wallet error

### ISSUE THREAD

**Issue by morfeli** [input-output-hk/nami#353]
Hello, 
I am having difficulties restoring my wallet with my protected seed phrases. Once after I have typed my phrases, the "next" button is disabled. All phrases are verified with a check mark. Please assist.

**Comment by HeptaSean** [comment]
All seed words come from a list of 2048 words. That the single words are verified just means that they are on the list.

But the seed phrase also contains a checksum. If that checksum does not fit, the next button stays greyed out.

You probably have mistyped or (worse) misread one of the words for another word that is also on the list. So, the checks for the single words are okay, but the checksum for the whole phrase does not fit.

The wordlist is: https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt You can look for likely close cousins of the words you are typing, e.g. "food" vs. "foot" (both on the list).

**Comment by morfeli** [comment]
Thank you-
