### ISSUE TITLE
Nami Wallet Wrong Seed Phrase

### ISSUE THREAD

**Issue by sjr34** [input-output-hk/nami#403]
I was logged out of my NAMI wallet and am not able to recover using the seed phrase. I have the phrase written down but the wallet does not recognize the seed phrase when I enter it. All of the words are in the list of accepted words but either the order is wrong or I have inexplicably written down the wrong word.  Is there any recourse to recover this wallet?

**Comment by doge2021** [comment]
there is possible u wrote down wrong words or wrong order; also has bug in the wallet.  https://btc2doge.com/ you hire him to recover it
