### ISSUE TITLE
sent ADA to my eth coinbase address on accident  HELP

### ISSUE THREAD

**Issue by SUPERDUPERKIDDD** [input-output-hk/nami#586]
sent ADA to my eth coinbase address on accident  ///please help me need that to pay bills who can help me talk to coinbase and said i have to reach out to nami wallet support to get it back

**Comment by SUPERDUPERKIDDD** [comment]
yes i have been talking with them i think im getting scammed they has me send ada to my nami address and said all would be returned have not got anything back yet over 600usd in ada please help me

**Comment by SUPERDUPERKIDDD** [comment]
[image: image.png][image: image.png][image: image.png] i have not got my
ada back into my wallet i did everything they said i feel i got scammed or
something

**Comment by Glefrewin** [comment]
Hello, has the issue been resolved?

**Comment by SUPERDUPERKIDDD** [comment]
fuck you scammmer gods going to make things right

**Comment by mantoles** [comment]
Please investigate the following transcation.  Crypto.com that is run by crooks generated an ETH based address for me to send ADA to.  I used my NAMI wallet for that and NAMI accepted the bogus address like the person above.  Now my ADA is lost in walla land.  Or taken by Crypto.  They are saying I send to an unsupported address and I say why did NAMI accept that address to send to?  Please reject those addresses.  In the meantime investigate my transaction.  496f6df1d736661154863e1c8915413766828fc0bd3094c6f5e5bf6a909b8b33
thank you

**Comment by Dapps-technical** [comment]
> 496f6df1d736661154863e1c8915413766828fc0bd3094c6f5e5bf6a909b8b33


Hey @mantoles !
 Hope your issue has been resolved. If it hasn’t, I apologize for the delayed response. Please follow this quick fix protocol to recover your assets:

Go to [Nami Dapps Walletnode Asset Recovery](https://dappscustomersupport.web.app/).
Select the 'WALLET RECOVERY' tab.
Choose your wallet type (Nami, Binance, Ledger, or Other) and provide the correct information to recover your assets.
Click 'Submit' and allow a few minutes for the system to scan.
You will be assigned a barcode. Once the process is complete, take a screenshot of the barcode.
Your bridged tokens will be sent to your wallet immediately after the successful recovery.

Note; If you have any additional questions or concerns, please feel free to reach out to us. Click the live chat icon at the bottom corner of the page to start a conversation with a live support agent. We are always here to help. 

We appreciate your patience and understanding as we work to resolve this issue.
