### ISSUE TITLE
How do I get the Wallet's PubKey?

### ISSUE THREAD

**Issue by rumourscape** [input-output-hk/nami#73]

**Comment by alessandrokonrad** [comment]
You can't right now, unless you open the developer console and type in `chrome.storage.local.get(console.log)`. You should be able to find the public key for each derived account.

**Comment by rumourscape** [comment]
Will it be added in the near future. Because I want to pass the wallet's address to Plutus but I think it only accepts PubKey afaik.

**Comment by alessandrokonrad** [comment]
You are probably talking about the public key hash. You can derive that one from an address.
