### ISSUE TITLE
Wallet got hacked

### ISSUE THREAD

**Issue by civroot6** [input-output-hk/nami#802]
have not used my laptop for a couple of months, then when I checked my nami wallet my ADA is gone. There is a transaction that transferred my funds to a wallet then the wallet is no longer active. c9203c9582c287d63e167bba8c60112097713dc983b29fba964f73cce26b7bee

**Comment by HanthandEth** [comment]
@civroot6 Talk to Cardano Support on the [Live support page](https://explore-cardano.org) so that your issue can be looked into.

**Comment by civroot6** [comment]
@HanthandEth who are they? and who are you? I think another scam

**Comment by civroot6** [comment]
> @civroot6 Talk to Cardano Support on the [Live support page](https://explore-cardano.org) so that your issue can be looked into.

another scammer, pretending to be a support. they will ask you to import wallet and enter your seedphrase. Beware of this website

**Comment by Henkzonfire** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by FredmanOwen** [comment]
Had similar case but thank my stars i was able to recover mines through the help of this man bohdanbohdan93 @ mail . ru
i hope he can help you too just reach out to him

**Comment by GarettBill** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by Cryptolord123** [comment]
> have not used my laptop for a couple of months, then when I checked my nami wallet my ADA is gone. There is a transaction that transferred my funds to a wallet then the wallet is no longer active. c9203c9582c287d63e167bba8c60112097713dc983b29fba964f73cce26b7bee
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by Williamalong23** [comment]
Quickly massage 22 cracker on Instagram for quick recovery now https://instagram.com/22cracker?igshid=YWYwM2I1ZDdmOQ==

**Comment by Bendy127** [comment]
So sorry about what happened same thing happened to me my wallet got hacked and about 0.9 btc was stolen thanks to Mr John a whitehathacker who helped me recover all of it message him on telegram too t.me/Whitehathacker217
