### ISSUE TITLE
Creating transaction for signTx

### ISSUE THREAD

**Issue by arressaye** [input-output-hk/nami#83]
Is there a way to create a transaction that can be passed into cardano.signTx without using CLI? I'm trying to build a site where users can simply click a button to buy an NFT and would like to take advantage of Nami's injected API to do this. What's the best way to create such a transaction from JS?

**Comment by mailtodanish** [comment]
@arressaye  you are able to do it I am also trying to create TX and sign using nami for my site? any clue?

**Comment by arressaye** [comment]
@mailtodanish yeah I've managed to do it using serialization lib.

**Comment by mailtodanish** [comment]
@arressaye  please share your approach/codes I will use same way.. I have tried serialization lib but no success.

**Comment by plutownium** [comment]
Is there example code for how to do this?

https://www.cardano-caniuse.io/ says: api.submitTx(tx: cbor<transaction>): Promise<hash32> I want to use this but i dont know how to make the "cbor<transaction>" part
