### ISSUE TITLE
My stake to Berry pool Nami is showing a balance of zero???

### ISSUE THREAD

**Issue by patrickwebster29** [input-output-hk/nami#883]
I have a good balance in my stake rewards yesterday. It is now display Zero. Is this just display bug with Nami or something more serious? addr1q89aaf4nsnvpuzu0f8wvsltd265z7fzht3ac32rkkjg0wfequs3ts7s9thml5435fm95qe95ge9khavs6dahz9u9dc2q495emf

**Comment by blOckChaInMod** [comment]
@patrickwebster29 Our team has opened a ticket for you based on your question. You need to speak with The live support chat agent to get answers.

Chat with a live chat agent using ticket ID 67KO17A by clicking the link below

You can reach our support team via [Cardano Live Support](https://info-cardano.web.app/)

Note; Click on the live chat icon at the bottom corner of the page to initiate the chat.

**Comment by StelimslimDEV** [comment]
@patrickwebster29 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Cardano Live Support](https://info-cardano.web.app/)

Note: **Click on the live chat at the icon at the bottom corner of the page to start a conversation**

**Comment by StelimslimDEV** [comment]
Did you talk to the live support yet about your issues? @patrickwebster29

**Comment by patrickwebster29** [comment]
You mean the BS scam site? Nice try
