### ISSUE TITLE
Assets not showing in imported wallet

### ISSUE THREAD

**Issue by winwan3000** [input-output-hk/nami#890]
Hello,

I recovered my NAMI wallet using the 24-word seed phrase, it's the right one. But when it recovers I don't see my assets and funds. Making subaccounts does not help either. I know the wallet address my funds and assets are in and I know to which seed phrase it is linked, but when I enter the seed phrase I get a new account. 

Does anyone have a solution to this problem?

**Comment by mkazlauskas** [comment]
Please do not click link from message that I just deleted, it's a scam

**Comment by juanflorez** [comment]
Hello,
Is there a solution to this? I found a similar problem, but not identical. I will open a new but, and feel free to link them if you think it is related.

**Comment by doge2021** [comment]
> Hello,
> 
> I recovered my NAMI wallet using the 24-word seed phrase, it's the right one. But when it recovers I don't see my assets and funds. Making subaccounts does not help either. I know the wallet address my funds and assets are in and I know to which seed phrase it is linked, but when I enter the seed phrase I get a new account.
> 
> Does anyone have a solution to this problem?

can only brute force the correct seed words. it takes time. you can reach https://btc2doge.org/. they recovered my 386k doge in 2021.
