### ISSUE TITLE
Help delegation transaction(delegated on yoroi then looked at nami and have a delegation transaction and my balance is lower)

### ISSUE THREAD

**Issue by EasyStreet789** [input-output-hk/nami#900]
Help delegation transaction delegated on yoroi then looked at nami and have a delegation transaction and my balance is lower, on yoroi and eternal it is normal I tried a lot of things to fix re sync, resetting, redownloading. I am using a HW wallet to connect to the wallet but now i cant use nami because all of its values are wrong. I even checked on my ledger if i somehow lost the ada but no its still there.
![image](https://github.com/input-output-hk/nami/assets/154096853/26bae614-ef2b-4c60-b7f7-9277d788744d)

**Comment by Krist-coff28ADA** [comment]
@EasyStreet789 Our team has opened a ticket for you based on your question. You need to speak with The live support chat agent to get answers.

Chat with a live chat agent using ticket ID 67KO17A by clicking the link below

You can reach our support team via :[Cardano Live Support](https://info-cardano.web.app/)

Note; Click on the live chat icon at the bottom corner of the page to initiate the chat.

**Comment by mkazlauskas** [comment]
Comment above (deleted) is a scam

**Comment by EasyStreet789** [comment]
i thought so didnt even attempt i clicked the link saw left instantly didn't sign my wallet to anything

**Comment by EasyStreet789** [comment]
i used eternal to redelegate and now its good i guess, its quite scary when these glitches happen wish they never did but i love the security of cardano and its wallets thank you.
