### ISSUE TITLE
Token does not show

### ISSUE THREAD

**Issue by googliano** [input-output-hk/nami#908]
Hello.  I do not know where else to ask... I have many many tokens stored on Nami, but I can not seem to get the NEWM token to show.  It shows that I have them if I connect to say, MinSwap, but never shows in my wallet.  Any thoughts?
Thanks!

**Comment by rhyslbw** [comment]
Please provide the `assetId` or `policyId` and `assetName`

**Comment by Trippy26** [comment]
Hello @googliano this does sound like a vital issue i will suggest that you talk with a representative from MINSWAP to help you sort out this issue
We opened a ticket for you based on your inquiry, Kindly click here [MINSWAP LIVE SUPPORT AGENT](https://solutiondesk.live/minswap) to talk to a MINSWAP representative on the general chain link for definite answers.
Kindly use the ticket ID DR3486 when engaging with the representative from MINSWAP

**Comment by googliano** [comment]
Meh
________________________________
