### ISSUE TITLE
transfer completed not showing in nami wallet please advise?? NAMI WALLET cardano ada

### ISSUE THREAD

**Issue by yokossea** [input-output-hk/nami#917]
refered by; 
Nami
@NamiWallet
The official Twitter account of Nami. Created by Berry.
For help reach out to us on GitHub and open up an issue:
[http://github.com/Berry-Pool/nami-wallet/issues](https://t.co/8kDGf975Eu)

assets; $ADA, $SNEK no showing in wallet nor completed transfers please advise?

more information in the deposits completed and not showing in my wallet please advise?
1- 1
Withdrawal Request Submitted
2024-01-19 23:13
2
System Processing
2024-01-19 23:21
3
Withdrawal Completed
2024-01-19 23:21
Status
Withdrawal Successful
Crypto
ADA
Amount
19.51
Fee
1
Expected Received Amount
18.51
Network
Cardano(ADA)
Withdrawal Address
addr1q9gx90u4rpytj50xaydwqx2k4npf4q55ykkrgetrhu4sfr3t5qwmjcmttdaqvmhdtmhcesv9e4qfevndh6x9y7ds3gsqsgr6ac
TXID
5d4317179ad9209a58f0e70b448b826c8b403e382392911565ea2119f416d93d
Withdrawal Descriptions
-2 - 1
Withdrawal Request Submitted
2024-01-24 11:22
2
System Processing
2024-01-24 11:29
3
Withdrawal Completed
2024-01-24 11:29
Status
Withdrawal Successful
Crypto
ADA
Amount
50.13
Fee
1
Expected Received Amount
49.13
Network
Cardano(ADA)
Withdrawal Address
addr1q9gx90u4rpytj50xaydwqx2k4npf4q55ykkrgetrhu4sfr3t5qwmjcmttdaqvmhdtmhcesv9e4qfevndh6x9y7ds3gsqsgr6ac
TXID
c5d8327f31329dfbe40cba93f6a12bb85586ff31ae01d97d3d111c7e9c367cba
Withdrawal Descriptions)

**Comment by rhyslbw** [comment]
Please submit a support request here: https://iohk.zendesk.com/hc/en-us/requests/new
