### ISSUE TITLE
How to disconnect from dAPP using javascript?

### ISSUE THREAD

**Issue by harniy** [input-output-hk/nami#924]
Hello, please tell me how to disconnect the wallet from the client side? In my application I made a connect button and the wallet connected perfectly, but how can I disconnect when clicked? I didn't find the disconnect method. thanks for the help

**Comment by rhyslbw** [comment]
Nami implements [CIP-30](https://cips.cardano.org/cip/CIP-30/). "Disconnecting" is achieved by simply discarding the API object returned from the `.enable` method.
