### ISSUE TITLE
Infinity Loading Send Screen Preprod

### ISSUE THREAD

**Issue by obscureera** [input-output-hk/nami#933]
At "Send" Screen, the amount input does not allow to input any amount since it's loading never ends.
It occurs at preprod network,.
Does not occurs in Mainnet.

Steps to reproduce:

 - Set your network to preprod.
 - Click "Send"/ Try to make a transaction.

![image](https://github.com/input-output-hk/nami/assets/171504782/fe812d8d-9457-46ea-a09c-82a97e7084fc)

**Comment by obscureera** [comment]
isAddressAllowed request does not return response.
empty "address" queryPram
![image](https://github.com/input-output-hk/nami/assets/171504782/900b0556-36ab-4841-97ed-b3b22da417a2)
![image](https://github.com/input-output-hk/nami/assets/171504782/a6027486-f0de-4377-954a-35af0722f348)

**Comment by obscureera** [comment]
Timeout
![image](https://github.com/input-output-hk/nami/assets/171504782/094fd4c8-2a59-4eb3-8664-113064eb342c)

**Comment by rhyslbw** [comment]
Fixed in 3.7.4
