### ISSUE TITLE
524 Timeout on isAddressAllowed call, unable to make transactions

### ISSUE THREAD

**Issue by obscureera** [input-output-hk/nami#935]
isAddressAllowed call taking to long to respond.
Also queryParam "address" is empty

![image](https://github.com/input-output-hk/nami/assets/171504782/6b5de5e5-8cbc-4662-8779-0a0a50204aeb)
![image](https://github.com/input-output-hk/nami/assets/171504782/ff4100e1-f502-430e-aad4-916f5438cb94)

**Comment by rhyslbw** [comment]
Fixed in 3.7.4
