### ISSUE TITLE
Trezor Safe 5 is not supported

### ISSUE THREAD

**Issue by Hannsek** [input-output-hk/nami#951]
I want to connect Trezor Safe 5 to the Nami wallet. I assume you have some internal check for Trezor devices there which do not include Trezor Safe 5 and say "Device is not a Trezor".

![image](https://github.com/user-attachments/assets/6fb872bb-9550-478f-beb6-908ed1d01a50)

**Comment by Aster36-kEth** [comment]
@Hannsek Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cardano-zendesk.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by rhyslbw** [comment]
Thanks for the report. We're preparing a fix now

**Comment by Hannsek** [comment]
@rhyslbw Thank you for quick reaction! Appreciate it.

I also noticed that you use our old logo. If you have some time, it would be great if you can replace it by our [new one](https://satoshilabs.visualbook.pro/en/trezor/logos/main-logo). Cheers.
